### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by TuXPick** [L1nuxDotFun/spacehook#16] opened 2019-08-25 19:29 UTC
I was able to build it few weeks ago, but now it's just giving me an error.

Running arch linux

I see few people are having the same issue as me

**Comment by koutsie** [comment] 2019-08-26 07:50
Duplicate of https://github.com/L1nuxDotFun/spacehook/issues/15

Closing this.

**Closed** 2019-08-26 07:51 UTC
