### ISSUE TITLE
can't compile on Arch Linux sixty-four bit

### ISSUE THREAD

**Issue by ElectfriedTheGod** [L1nuxDotFun/spacehook#13] opened 2019-07-29 10:11 UTC
![Screenshot_2019-07-29_00-11-22](https://user-images.githubusercontent.com/37424196/62040478-54239a00-b1bf-11e9-9c53-0f3defb7d684.png)

**Comment by koutsie** [comment] 2019-08-26 07:51
Duplicate of https://github.com/L1nuxDotFun/spacehook/issues/15


Closing this.

**Closed by koutsie** 2019-08-26 07:51 UTC
